[package]
name = "hello-wasm"
version = "0.1.0"
description = "A sample project with wasm-pack"
edition = "2024"
repository = "https://github.com/GigiQuess/hello-wasm"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"